### ISSUE TITLE
Use in HashMap

### ISSUE THREAD

**Issue by luke-titley** [anderslanglands/ustr#1]
Hey,
Thanks again for writing ustr, I'm using it for all object names at the moment in a hobby project I'm working on. Seems to be working okay at the moment, but I have as yet to profile and measue the project properly before I'll be able to give any good feedback.

A quick question.

I need to use this type as a key in a HashMap. Is this how you'd recommend implementing the hash trait for it? Its a bit funny re-hashing the hash but...

```
impl Hash for Ustr {
    fn hash<H: Hasher>(&self, hasher: &mut H) {
        self.precomputed_hash().hash(hasher)
    }
}
```
Just wondering what your thoughts are on this.

**Comment by anderslanglands** [comment]
Hi Luke, sorry I missed this issue earlier! There are actually dedicated HashMap and HashSet type aliases in https://github.com/anderslanglands/ustr/blob/master/src/hash.rs so that the precomputed hash can be used directly. This seemed to be the easiest way to do it. I still need to look into allowing to configure the hash function as a feature as well (which would just be selected one from the fastshash crate, or using Rust' default).

**Comment by anderslanglands** [comment]
Incidentally I just pushed my latest changes which tweaks the API a little - u! macro is replaced by ustr() short function being the main one.

**Comment by luke-titley** [comment]
Ah great. I must have missed the hash.rs file.
