### ISSUE TITLE
Unit test failure in 'tests::blns'

### ISSUE THREAD

**Issue by luke-titley** [anderslanglands/ustr#4]
Hey,
I'm getting a unit test failure in tests::blns.
I'm on a mac (mojave 10.14.10).

This is on the master and serde branches.

Release and debug builds.

```
running 6 tests
test hash::test_hashing ... ok
test tests::c_str_works ... ok
test tests::it_works ... ok
test tests::empty_string ... ok
test tests::blns ... FAILED
test tests::raft ... ok

failures:

---- tests::blns stdout ----
thread 'tests::blns' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1315`', src/lib.rs:467:9
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: std::panicking::begin_panic_fmt
   5: ustr::tests::blns
   6: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
   7: __rust_maybe_catch_panic
   8: test::run_test::run_test_inner::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by luke-titley** [comment]
```
 // check that the number of entries is the same
assert_eq!(super::num_entries(), hs.len());
```

**Comment by anderslanglands** [comment]
Did you run it with

> RUST_TEST_THREADS=1 cargo test

?

**Comment by luke-titley** [comment]
Everything passes when it's all on one thread.

**Comment by anderslanglands** [comment]
Great!

**Comment by luke-titley** [comment]
Is it intended to be thread safe ?

**Comment by anderslanglands** [comment]
Yes, and it is.

What's happening is that some of the tests put, say, 5 strings in the
cache, then check that there actually are 5 strings in the cache. This is
fine when you run the tests on a single thread, but if multiple tests are
running concurrently, then when the check happens there could be any number
of strings in the cache because other tests are adding strings at the same
time. This is to be expected and is still thread-safe, it's just not great
for unit testing.

**Comment by luke-titley** [comment]
Aaah, right. Great!

**Comment by luke-titley** [comment]
Ah, I'm a fool. You already wrote this in the README.md

**Comment by anderslanglands** [comment]
No worries :)
